format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$fill\
$cmd_duration\
$time
$character"""

add_newline = false
palette = "catppuccin_mocha"

[directory]
style = "mauve"

[character]
success_symbol = "[❯](rosewater)"
error_symbol = "[X](red)"
vimcmd_symbol = "[](rosewater)"

[git_branch]
format = "[$branch]($style)"
style = "overlay0"

[git_state]
format = '\([$state($progress_current/$progress_total)]($style)\)'
style = "overlay0"

[git_status]
format = '([$all_status$ahead_behind]($style))'
modified = 'M'
conflicted = '󱃞'
style = "peach"

[git_metrics]
format = '([+$added]($added_style))([-$deleted]($deleted_style))'
disabled = false
added_style = "bold mauve"
deleted_style = "bold red"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[fill]
symbol = '-'
style = 'surface0'

[time]
disabled = false
format = '[$time]($style)'
# time_format = '%H:%M:%S%.3f'
time_format = '%H:%M:%S'
style = "bold rosewater"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#0e1117"
mantle = "#181825"
crust = "#11111b"
