format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$fill\
$cmd_duration\
$time
$character"""

add_newline = false

[directory]
style = "blue"

[character]
success_symbol = "[❯](yellow)"
error_symbol = "[X](red)"
vimcmd_symbol = "[](white)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = '\([$state($progress_current/$progress_total)]($style)\)'
style = "bright-black"

[git_status]
format = '([$all_status$ahead_behind]($style))'
modified = 'M'
conflicted = '󱃞'

[git_metrics]
format = '([+$added]($added_style))([-$deleted]($deleted_style))'
disabled = false

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[fill]
symbol = '-'
style = 'bright-black'

[time]
disabled = false
format = '[$time]($style)'
# time_format = '%H:%M:%S%.3f'
time_format = '%H:%M:%S'
